# Generated by Django 5.1.7 on 2025-03-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("langchain_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatexchange",
            name="session_id",
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
