# Generated by Django 5.1.7 on 2025-03-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("langchain_api", "0002_alter_chatexchange_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatexchange",
            name="session_id",
            field=models.CharField(max_length=255),
        ),
    ]
