# Generated by Django 5.1.7 on 2025-03-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("langchain_api", "0002_rename_sessionchat_chatexchange"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="chatexchange",
            table="chat_exchange",
        ),
    ]
